name: gather_perf
channels:
 - conda-forge
 - bioconda
dependencies:
 - python=3.6.5
 - psutil=5.2.2
 - snakemake=5.2.0
 - notebook=5.6.0
 - jupyterlab=0.32.1
 - pandas=0.20.3
 - qgrid=1.1.1
 - seaborn=0.9.0
 - pip:
   - git+https://github.com/ssanderson/pstats-view.git#egg=pstatsview
